### ISSUE TITLE
Newsfeed of what?

### ISSUE THREAD

**Issue by brianzelip** [j-p-courneya/relayMDWebsite_Planning#2]
website-outline.md asks

> How to integrate a newsfeed?

Where is the news coming from? There will likely be an API to call.

**Comment by brianzelip** [comment]
I see - later in the doc it's mentioned that this content would come from a listserv. Is this a community wide list serv, or official RIA only?

Content in an email may or may not be formatted and ready to go for publication on the web. You'll likely need to manually enter content into the website if the data source is a general community wide email list.

**Comment by j-p-courneya** [comment]
Email is received at a Gmail account. That is forwarded to a distribution list within Gmail. I considered maybe they're could be a firm for prime to submit news. However worried about being spammed
